import 'dart:io';
import 'package:shared_preferences/shared_preferences.dart';
import '../utils/txa_logger.dart';

class TxaLanguage {
  static String _currentLang = 'vi';
  static final Map<String, Map<String, String>> _dicts = {
    'vi': {
      'app_name': 'TPhimX Premium',
      'ok': 'Đồng ý',
      'cancel': 'Hủy bỏ',
      'check_update': 'Kiểm tra cập nhật',
      'downloading': 'Đang tải xuống...',
      'error': 'Lỗi',
      'success': 'Thành công',
      'permissions_required': 'Yêu cầu quyền truy cập',
      'storage_permission_msg': 'Ứng dụng cần quyền quản lý tệp để lưu nhật ký và tải ứng dụng.',
      'grant': 'Cấp quyền',
      'skip': 'Bỏ qua',
      'retry': 'Thử lại',
      'network_error': 'Không có kết nối mạng',
      'update_available': 'Có bản cập nhật mới',
      'update_now': 'Cập nhật ngay',
      'later': 'Để sau',
      'no_movies': 'Không tìm thấy phim nào',
      'error_loading_data': 'Không thể tải dữ liệu',
      'new_update_movies': 'Phim mới cập nhật',
      'hot_movies': 'Phim hot',
      'anime_cartoon': 'Anime & Hoạt hình',
      'series_movies': 'Phim bộ mới',
      'single_movies': 'Phim lẻ mới',
      'cartoon_movies': 'Hoạt hình mới',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Phim chiếu rạp',
      'search': 'Tìm kiếm',
      'home': 'Trang chủ',
      'schedule': 'Lịch chiếu',
      'profile': 'Cá nhân',
      'app_premium': 'Mobile Premium',
      'connecting': 'Đang kết nối...',
      'retry_connection': 'Thử lại kết nối',
      'more': 'Thêm',
      'watch_now': 'Xem phim',
      'add_favorite': 'Yêu thích',
      'trending_categories': 'Bạn đang quan tâm gì?',
      'see_all': 'Xem tất cả',
      'permission_storage_label': 'Quản lý tệp & Bộ nhớ',
      'permission_storage_desc': 'Bắt buộc để tải xuống phim và lưu nhật ký ứng dụng.',
      'permission_notif_label': 'Thông báo đẩy',
      'permission_notif_desc': 'Nhận thông báo khi có tập phim mới hoặc lịch chiếu.',
      'permission_install_label': 'Cài đặt ứng dụng',
      'permission_install_desc': 'Bắt buộc để ứng dụng có thể tự động nâng cấp phiên bản mới.',
      'press_back_again': 'Nhấn lần nữa để thoát ứng dụng',
      'player_settings': 'Cài đặt trình phát',
      'language': 'Ngôn ngữ',
      'select_language': 'Chọn ngôn ngữ',
      'vi_lang': 'Tiếng Việt',
      'en_lang': 'Tiếng Anh',
      'loading_progress': 'Đang chuẩn bị dữ liệu...',
      'check_permissions': 'Kiểm tra quyền truy cập',
      'please_grant_all': 'Vui lòng cấp các quyền bắt buộc để tiếp tục.',
      'go_to_settings': 'Vào cài đặt',
      'feature_dev': 'Tính năng đang phát triển',
      'feature_under_dev': 'Tính năng "%label" đang được phát triển',
      'coming_soon': 'Tính năng đang phát triển',
      'coming_soon_msg': 'Tính năng này sẽ sớm ra mắt trong các bản cập nhật tới. Vui lòng quay lại sau nhé!',
      'episodes': 'Tập phim',
      'episode': 'Tập',
      'loading_home': 'Đang tải trang chủ...',
      'loading_movie': 'Đang tải thông tin phim...',
      'all_movies_count': '%count phim',
      'recommendation': 'Đề xuất',
      'no_episodes': 'Không có tập phim nào',
      'not_found_movie': 'Không tìm thấy phim',
      'select_server': 'Chọn Server',
      'related_parts': 'Chọn phần nào',
      'series_parts': 'Chọn phần nào',
      'actors': 'Diễn viên',
      'no_actors': 'Chưa cập nhật diễn viên',
      'download': 'Tải xuống',
      'share': 'Chia sẻ',
      'favorite_list': 'Yêu thích',
      'collapse': 'Thu gọn',
      'show_more': 'Xem thêm',
      'broadcast_msg': '%prefix sẽ phát sóng vào %time. Các bạn nhớ đón xem nhé 😙',
      'broadcast_final_msg': 'Đừng bỏ lỡ %prefix (Hồi kết) sẽ phát sóng vào %time 🥹',
      'broadcast_suffix': 'Phim sẽ phát sóng tập tiếp theo vào %time. Các bạn nhớ đón xem nhé 😙',
      'final_ep': 'Tập cuối',
      'final_part': 'Hồi kết',
      'current_version': 'Phiên bản hiện tại: %version',
      'up_to_date': 'Bạn đang sử dụng phiên bản mới nhất (%version)',
      'update_error': 'Lỗi kiểm tra cập nhật',
      'checking_update': 'Đang kiểm tra cập nhật...',
      'whats_new': 'Có gì mới:',
      'version_label': 'Phiên bản %version',
      'volume': 'Âm lượng',
      'speed': 'Tốc độ',
      'skip_intro': 'Bỏ qua Intro',
      'auto_next_ep': 'Tự động chuyển tập',
      'skip_outro_next': 'Bỏ qua Outro / Tập Tiếp',
      'prep_next_ep': 'Đang chuẩn bị tập tiếp theo...',
      'video_error': 'Lỗi tải video. Vui lòng thử lại!',
      'search_hint': 'Tìm phim, diễn viên...',
      'searching': 'Đang tìm kiếm...',
      'search_results': 'Kết quả (%count)',
      'search_no_results': 'Không tìm thấy kết quả cho "%query"',
      'search_hot_title': '🔥 Được tìm nhiều nhất',
      'search_input_prompt': 'Nhập từ khóa để tìm phim',
      'clear_filter': 'Xóa lọc',
      'category_label': 'Thể loại: %name',
      'views_count': '%count lượt',
      'movie_series': 'Phim bộ',
      'movie_single': 'Phim lẻ',
      'year_label': 'Năm %year',
      'today': 'Hôm nay',
      'loading_schedule': 'Đang tải lịch chiếu...',
      'no_schedule_today': 'Hôm nay chưa có lịch chiếu',
      'no_schedule_date': 'Không có lịch chiếu vào %date',
      'unknown_episode': 'Tập ???',
      'watching': 'Đang xem',
      'my_list_long': 'Danh sách phim của tôi',
      'tv_login': 'Đăng nhập SmartTV',
      'fb_fanpage': 'Fanpage Facebook',
      'tg_channel': 'Kênh Telegram',
      'tg_support': 'Nhóm Telegram (Hỗ trợ)',
      'terms_of_service': 'Điều khoản dịch vụ',
      'privacy_policy': 'Chính sách bảo mật',
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'account_title': 'Tài khoản',
      'save_changes': 'Lưu thay đổi',
      'not_open_link': 'Không thể mở liên kết',
      'close': 'Đóng',
      'cannot_download_update': 'Không thể tải bản cập nhật',
      'resolver_error': 'Lỗi resolver: %error',
      'no_sources_found': 'Không tìm thấy nguồn phát hợp lệ cho tập này.',
      'all_sources_failed': 'Tất cả các nguồn phát đều thất bại.',
      'TXA_PB1': 'Phim bộ mới',
      'TXA_PL1': 'Phim lẻ mới',
      'TXA_NEW1': 'Phim mới cập nhật',
      'TXA_HOT1': 'Phim hot',
      'TXA_HH1': 'Anime & Hoạt hình',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Phim chiếu rạp',
      'TXA_LIST1': 'Danh sách phim',
      'player_brightness': 'Độ sáng',
      'player_audio': 'Âm thanh',
      'player_lock': 'Khóa màn hình',
      'player_unlock': 'Mở khóa',
      'player_episodes': 'Danh sách tập',
      'player_gesture_hint': 'Vuốt để chỉnh độ sáng/âm lượng',
      'player_fast_forward_2x': 'Đang tua nhanh 2x',
      'player_seek_forward': 'Tua tới %count giây',
      'player_seek_backward': 'Tua lùi %count giây',
      'player_watermark': 'TPhimX Premium',
      'player_ratio': 'Tỷ lệ',
      'player_audio_track': 'Âm thanh',
      'player_seek_hint_short': 'Chạm đúp',
      'player_subtitle': 'Phụ đề',
      'current_label': 'Hiện tại',
      'server_switch_hint': 'Chọn server để xem ở nguồn khác',
      'server_ep_unavailable_title': 'Tập phim không khả dụng',
      'server_ep_unavailable_msg': 'Tập %ep chưa có trên server %server. Tự động chuyển về server mặc định.',
      'download_finished': 'Tải xong 🚀',
      'click_to_install': '(Bấm để cài đặt)',
      'error_opening_link': 'Không thể mở trình cài đặt hoặc liên kết',
      'udid_register_title': 'Nhập mã UDID',
      'udid_update_title': 'Cập nhật UDID',
      'udid_hint': 'Dán mã UDID tại đây...',
      'udid_save': 'Lưu lại',
      'udid_copy': 'Sao chép UDID',
      'udid_copied': 'Đã sao chép UDID',
      'udid_deleted': '✅ Đã xóa UDID!',
      'udid_delete_btn': 'Xóa UDID',
      'udid_install_btn': 'Cài đặt ngay',
      'udid_get_btn': 'Lấy UDID',
      'udid_input_btn': 'Nhập UDID',
      'udid_update_btn': 'Nhập UDID',
      'udid_registered_badge': 'ĐÃ ĐĂNG KÝ',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc': 'Cần đăng ký UDID thiết bị để có thể cài đặt và cập nhật bản IPA Premium chính thức.',
      'ios_ready_desc': 'Thiết bị của bạn đã được đăng ký UDID. Bạn có thể cài đặt phiên bản Premium IPA chính thức ngay bây giờ.',
    },
    'en': {
      'app_name': 'TPhimX Premium',
      'ok': 'OK',
      'cancel': 'Cancel',
      'check_update': 'Check for Updates',
      'downloading': 'Downloading...',
      'error': 'Error',
      'success': 'Success',
      'permissions_required': 'Permissions Required',
      'storage_permission_msg': 'App needs file management permission to save logs and download apps.',
      'grant': 'Grant',
      'skip': 'Skip',
      'retry': 'Retry',
      'network_error': 'No network connection',
      'update_available': 'New update available',
      'update_now': 'Update Now',
      'later': 'Later',
      'no_movies': 'No movies found',
      'error_loading_data': 'Failed to load data',
      'new_update_movies': 'Newest Movies',
      'hot_movies': 'Hot Movies',
      'anime_cartoon': 'Anime & Animation',
      'series_movies': 'New Series',
      'single_movies': 'New Singles',
      'cartoon_movies': 'Cartoons',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Theaters',
      'search': 'Search',
      'home': 'Home',
      'schedule': 'Schedule',
      'profile': 'Profile',
      'app_premium': 'Mobile Premium',
      'connecting': 'Connecting...',
      'retry_connection': 'Retry Connection',
      'more': 'More',
      'watch_now': 'Watch now',
      'add_favorite': 'Favorite',
      'trending_categories': 'What are you interested in?',
      'see_all': 'See All',
      'permission_storage_label': 'Storage & File Management',
      'permission_storage_desc': 'Required to download movies and save app logs.',
      'permission_notif_label': 'Push Notifications',
      'permission_notif_desc': 'Receive notifications for new episodes or schedules.',
      'permission_install_label': 'Install Applications',
      'permission_install_desc': 'Required for automatic version upgrades.',
      'press_back_again': 'Press back again to exit',
      'player_settings': 'Player Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'vi_lang': 'Vietnamese',
      'en_lang': 'English',
      'loading_progress': 'Preparing data...',
      'check_permissions': 'Checking permissions',
      'please_grant_all': 'Please grant required permissions to continue.',
      'go_to_settings': 'Go to Settings',
      'feature_dev': 'Feature under development',
      'feature_under_dev': 'Feature "%label" is under development',
      'coming_soon': 'Coming Soon',
      'coming_soon_msg': 'This feature will be available in future updates. Please check back later!',
      'episodes': 'Episodes',
      'episode': 'Episode',
      'loading_home': 'Loading homepage...',
      'loading_movie': 'Loading movie info...',
      'all_movies_count': '%count movies',
      'recommendation': 'Suggestions',
      'no_episodes': 'No episodes available',
      'not_found_movie': 'Movie not found',
      'select_server': 'Select Server',
      'related_parts': 'Which part?',
      'series_parts': 'Which part?',
      'actors': 'Cast',
      'no_actors': 'No cast info available',
      'download': 'Download',
      'share': 'Share',
      'favorite_list': 'Favorites',
      'collapse': 'Collapse',
      'show_more': 'Show more',
      'broadcast_msg': '%prefix will broadcast at %time. Don\'t miss it 😙',
      'broadcast_final_msg': 'Don\'t miss %prefix (Final) broadcasting at %time 🥹',
      'broadcast_suffix': 'Next episode will broadcast at %time. Stay tuned 😙',
      'final_ep': 'Final Episode',
      'final_part': 'Final',
      'current_version': 'Current Version: %version',
      'up_to_date': 'You are on the latest version (%version)',
      'update_error': 'Failed to check for updates',
      'checking_update': 'Checking for updates...',
      'whats_new': 'What\'s new:',
      'version_label': 'Version %version',
      'volume': 'Volume',
      'speed': 'Speed',
      'skip_intro': 'Skip Intro',
      'auto_next_ep': 'Auto Next Episode',
      'skip_outro_next': 'Skip Outro / Next',
      'prep_next_ep': 'Preparing next episode...',
      'video_error': 'Failed to load video. Please try again!',
      'search_hint': 'Search movies, actors...',
      'searching': 'Searching...',
      'search_results': 'Results (%count)',
      'search_no_results': 'No results found for "%query"',
      'search_hot_title': '🔥 Trending Searches',
      'search_input_prompt': 'Types keywords to find movies',
      'clear_filter': 'Clear filter',
      'category_label': 'Category: %name',
      'views_count': '%count views',
      'movie_series': 'Series',
      'movie_single': 'Single',
      'year_label': 'Year %year',
      'today': 'Today',
      'loading_schedule': 'Loading schedule...',
      'no_schedule_today': 'No schedule today',
      'no_schedule_date': 'No schedule on %date',
      'unknown_episode': 'Episode ???',
      'watching': 'Watching',
      'my_list_long': 'My Movie List',
      'tv_login': 'SmartTV Login',
      'fb_fanpage': 'Facebook Fanpage',
      'tg_channel': 'Telegram Channel',
      'tg_support': 'Telegram Support',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'login': 'Login',
      'register': 'Register',
      'account_title': 'Account',
      'save_changes': 'Save Changes',
      'not_open_link': 'Could not open link',
      'close': 'Close',
      'cannot_download_update': 'Could not download update',
      'resolver_error': 'Resolver error: %error',
      'no_sources_found': 'No valid streaming sources found for this episode.',
      'all_sources_failed': 'All streaming sources failed to load.',
      'TXA_PB1': 'New Series',
      'TXA_PL1': 'New Singles',
      'TXA_NEW1': 'Newly Updated',
      'TXA_HOT1': 'Hot Movies',
      'TXA_HH1': 'Anime & Cartoons',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Theatrical Movies',
      'TXA_LIST1': 'Movie List',
      'player_brightness': 'Brightness',
      'player_audio': 'Audio',
      'player_lock': 'Lock Screen',
      'player_unlock': 'Unlock',
      'player_episodes': 'Episode List',
      'player_gesture_hint': 'Swipe to adjust brightness/volume',
      'player_fast_forward_2x': 'Fast Forwarding 2x',
      'player_seek_forward': 'Seek forward %count s',
      'player_seek_backward': 'Seek backward %count s',
      'player_watermark': 'TPhimX Premium',
      'player_ratio': 'Ratio',
      'player_audio_track': 'Audio',
      'player_seek_hint_short': 'Double Tap',
      'player_subtitle': 'Subtitle',
      'current_label': 'Current',
      'server_switch_hint': 'Switch server to watch from another source',
      'server_ep_unavailable_title': 'Episode Unavailable',
      'server_ep_unavailable_msg': 'Episode %ep is not available on %server. Auto-switching to default server.',
      'download_finished': 'Download finished 🚀',
      'click_to_install': '(Click to install)',
      'error_opening_link': 'Could not open installer or link',
      'udid_register_title': 'Input UDID',
      'udid_update_title': 'Update UDID',
      'udid_hint': 'Paste UDID here...',
      'udid_save': 'Save',
      'udid_copy': 'Copy UDID',
      'udid_copied': 'UDID copied',
      'udid_deleted': '✅ UDID deleted!',
      'udid_delete_btn': 'Delete UDID',
      'udid_install_btn': 'Install Now',
      'udid_get_btn': 'Get UDID',
      'udid_input_btn': 'Input UDID',
      'udid_update_btn': 'Update',
      'udid_registered_badge': 'REGISTERED',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc': 'Need to register device UDID to install and update the official Premium IPA.',
      'ios_ready_desc': 'Your device is registered. You can install the official Premium IPA now.',
    }
  };

  static String get currentLang => _currentLang;

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString('txa_lang');
    if (saved != null) {
      _currentLang = saved;
    } else {
      // Automatic detection
      try {
        final locale = Platform.localeName.split('_')[0];
        if (_dicts.containsKey(locale)) {
          _currentLang = locale;
        } else {
          _currentLang = 'en'; // Default
        }
      } catch (_) {
        _currentLang = 'vi';
      }
    }
  }

  static Future<void> setLang(String lang) async {
    if (_dicts.containsKey(lang)) {
      _currentLang = lang;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('txa_lang', lang);
    }
  }

  static String t(String key) {
    if (_dicts[_currentLang]?[key] == null) {
      TxaLogger.log("Missing key '$key' for language '$_currentLang'", isError: true);
    }
    return _dicts[_currentLang]?[key] ?? _dicts['en']?[key] ?? key;
  }
}
