import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../utils/txa_logger.dart';

class TxaLanguage extends ChangeNotifier {
  static final TxaLanguage _instance = TxaLanguage._internal();
  factory TxaLanguage() => _instance;
  TxaLanguage._internal();

  static String _currentLang = 'vi';
  static Function()? onLanguageChanged;
  static final Map<String, Map<String, String>> _dicts = {
    'vi': {
      'preparing': 'Đang chuẩn bị...',
      'logout': 'Đăng xuất',
      'app_name': 'TPhimX Premium',
      'ok': 'Đồng ý',
      'cancel': 'Hủy bỏ',
      'clear': 'Xóa',
      'check_update': 'Kiểm tra cập nhật',
      'downloading': 'Đang tải',
      'downloading_status': 'Đang tải: %p%% • %s% • ETA: %e%',
      'error': 'Lỗi',
      'success': 'Thành công',
      'permissions_required': 'Yêu cầu quyền truy cập',
      'storage_permission_msg':
          'Ứng dụng cần quyền quản lý tệp để lưu nhật ký và tải ứng dụng.',
      'grant': 'Cấp quyền',
      'skip': 'Bỏ qua',
      'retry': 'Thử lại',
      'network_error': 'Không có kết nối mạng',
      'update_available': 'Có bản cập nhật mới',
      'update_now': 'Cập nhật ngay',
      'later': 'Để sau',
      'no_movies': 'Không tìm thấy phim nào',
      'error_loading_data': 'Không thể tải dữ liệu',
      'no_changelog': 'Chưa có lịch sử cập nhật',
      'new_update_movies': 'Phim mới cập nhật',
      'hot_movies': 'Phim hot',
      'anime_cartoon': 'Anime & Hoạt hình',
      'series_movies': 'Phim bộ mới',
      'single_movies': 'Phim lẻ mới',
      'cartoon_movies': 'Hoạt hình mới',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Phim chiếu rạp',
      'search': 'Tìm kiếm',
      'home': 'Trang chủ',
      'categories': 'Thể loại',
      'schedule': 'Lịch chiếu',
      'logs': 'Nhật ký',
      'clear_logs_confirm': 'Xóa toàn bộ nhật ký?',
      'clear_logs_msg': 'Hành động này sẽ xóa tất cả tệp log hiện có.',
      'no_logs_found': 'Không tìm thấy nhật ký nào.',
      'profile': 'Cá nhân',
      'app_premium': 'Mobile Premium',
      'connecting': 'Đang kết nối...',
      'retry_connection': 'Thử lại kết nối',
      'more': 'Thêm',
      'watch_now': 'Xem phim',
      'add_favorite': 'Yêu thích',
      'trending_categories': 'Bạn đang quan tâm gì?',
      'see_all': 'Xem tất cả',
      'permission_storage_label': 'Quản lý tệp & Bộ nhớ',
      'permission_storage_desc':
          'Bắt buộc để tải xuống phim và lưu nhật ký ứng dụng.',
      'permission_notif_label': 'Thông báo đẩy',
      'permission_notif_desc':
          'Nhận thông báo khi có tập phim mới hoặc lịch chiếu.',
      'permission_install_label': 'Cài đặt ứng dụng',
      'permission_install_desc':
          'Bắt buộc để ứng dụng có thể tự động nâng cấp phiên bản mới.',
      'permission_overlay_desc':
          'Quyền này cần thiết để chế độ PiP (thu nhỏ) có thể hoạt động khi bạn thoát app.',
      'permission_nearby_devices_label': 'Thiết bị ở gần (Nearby)',
      'permission_nearby_devices_desc':
          'Bắt buộc để tìm kiếm và kết nối với các thiết bị Cast/TV trong mạng local.',
      'permission_bluetooth_label': 'Bluetooth (Dò thiết bị)',
      'permission_bluetooth_desc':
          'Cần thiết để phát hiện các thiết bị truyền tải không dây xung quanh.',
      'permission_nearby_devices_denied':
          'Quyền truy cập thiết bị ở gần bị từ chối. Không thể dò TV.',
      'pip_permission_missing': 'Thiếu quyền vẽ lên ứng dụng khác để bật PiP.',
      'screenshot_detected': 'Đã chụp màn hình',
      'share_screenshot': 'Chia sẻ ảnh chụp',
      'pip_mode': 'Chế độ thu nhỏ',
      'now_playing_pip': 'Đang phát: %title%',
      'press_back_again': 'Nhấn lần nữa để thoát ứng dụng',
      'player_settings': 'Cài đặt trình phát',
      'language': 'Ngôn ngữ',
      'select_language': 'Chọn ngôn ngữ',
      'vi_lang': 'Tiếng Việt',
      'en_lang': 'Tiếng Anh',
      'loading_progress': 'Đang chuẩn bị dữ liệu...',
      'splash_check_permissions': 'Kiểm tra quyền truy cập...',
      'splash_init_language': 'Khởi tạo ngôn ngữ...',
      'splash_config_system': 'Cấu hình hệ thống...',
      'splash_init_download': 'Khởi tạo trình tải xuống...',
      'splash_ios_no_access': 'Bạn chưa có quyền truy cập ứng dụng này.',
      'splash_init_failed': 'Khởi tạo thất bại',
      'splash_error_title': 'Oops! Đã có lỗi xảy ra',
      'splash_error_copy': 'Copy Lỗi',
      'splash_error_copied': 'Đã copy mã lỗi!',
      'splash_browser_error': 'Không thể mở trình duyệt',
      'splash_get_access': 'Lấy quyền truy cập ứng dụng',
      'splash_safari_note':
          'Lưu ý: Bạn cần cài đặt Profile xác minh sau khi mở Safari.',
      'maintenance_title': 'Hệ thống đang bảo trì',
      'maintenance_msg':
          'Chúng tôi đang nâng cấp hệ thống để mang lại trải nghiệm tốt hơn. Vui lòng quay lại sau ít phút.',
      'check_permissions': 'Kiểm tra quyền truy cập',
      'please_grant_all': 'Vui lòng cấp các quyền bắt buộc để tiếp tục.',
      'go_to_settings': 'Vào cài đặt',
      'permissions_mandatory': 'Quyền bắt buộc',
      'permissions_optional': 'Quyền tùy chọn',
      'granted': 'Đã cấp',
      'denied': 'Chưa cấp',
      'continue': 'Tiếp tục',
      'permission_location_label': 'Vị trí',
      'permission_location_desc': 'Yêu cầu để kiểm tra tốc độ mạng chính xác.',
      'permission_nearby_label': 'Thiết bị ở gần',
      'permission_nearby_desc': 'Dùng để tìm và truyền video lên TV (Cast).',
      'speed_test_error':
          'Không thể bắt đầu kiểm tra tốc độ. Vui lòng cấp quyền vị trí hoặc thử lại sau.',
      'feature_dev': 'Tính năng đang phát triển',
      'feature_under_dev': 'Tính năng "%label" đang được phát triển',
      'coming_soon': 'Tính năng đang phát triển',
      'coming_soon_msg':
          'Tính năng này sẽ sớm ra mắt trong các bản cập nhật tới. Vui lòng quay lại sau nhé!',
      'episodes': 'Tập phim',
      'episode': 'Tập',
      'loading_home': 'Đang tải trang chủ...',
      'loading_movie': 'Đang tải thông tin phim...',
      'all_movies_count': '%count% phim',
      'recommendation': 'Đề xuất',
      'no_episodes': 'Không có tập phim nào',
      'not_found_movie': 'Không tìm thấy phim',
      'select_server': 'Chọn Server',
      'related_parts': 'Chọn phần nào',
      'series_parts': 'Chọn phần nào',
      'actors': 'Diễn viên',
      'no_actors': 'Chưa cập nhật diễn viên',
      'download': 'Tải xuống',
      'download_label': 'Tốc độ tải xuống',
      'upload_label': 'Tốc độ tải lên',
      'share': 'Chia sẻ',
      'favorite_list': 'Yêu thích',
      'collapse': 'Thu gọn',
      'show_more': 'Xem thêm',
      'broadcast_msg':
          '%prefix% sẽ phát sóng vào %time%. Các bạn nhớ đón xem nhé 😙',
      'broadcast_final_msg':
          'Đừng bỏ lỡ %prefix% (Hồi kết) sẽ phát sóng vào %time% 🥹',
      'broadcast_suffix':
          'Phim sẽ phát sóng tập tiếp theo vào %time%. Các bạn nhớ đón xem nhé 😙',
      'final_ep': 'Tập cuối',
      'final_part': 'Hồi kết',
      'current_version': 'Phiên bản hiện tại: %version%',
      'update_history': 'Lịch sử cập nhật',
      'general_settings': 'Cài đặt chung',
      'app_settings': 'Cài đặt ứng dụng',
      'community_support': 'Cộng đồng & Hỗ trợ',
      'legal': 'Pháp lý',
      'clear_cache_msg':
          'Bạn có chắc chắn muốn xóa bộ nhớ tạm? Hành động này sẽ giải phóng dung lượng nhưng không ảnh hưởng đến dữ liệu đã lưu.',
      'session_expired': 'Phiên đăng nhập hết hạn',
      'load_error': 'Lỗi tải thông tin',
      'login_again_msg': 'Vui lòng đăng nhập lại để tiếp tục',
      'up_to_date': 'Bạn đang sử dụng phiên bản mới nhất (%version%)',
      'update_error': 'Lỗi kiểm tra cập nhật',
      'checking_update': 'Đang kiểm tra phiên bản mới...',
      'whats_new': 'Có gì mới:',
      'version_label': 'Phiên bản %version%',
      'volume': 'Âm lượng',
      'speed': 'Tốc độ',
      'skip_intro': 'Bỏ qua Intro',
      'auto_next_ep': 'Auto Next Tập Tiếp',
      'skip_outro_next': 'Bỏ qua Outro / Tập Tiếp',
      'prep_next_ep': 'Đang chuẩn bị tập tiếp theo...',
      'video_error': 'Lỗi tải video. Vui lòng thử lại!',
      'search_hint': 'Tìm phim, diễn viên...',
      'searching': 'Đang tìm kiếm...',
      'search_results': 'Kết quả (%count%)',
      'search_no_results': 'Không tìm thấy kết quả cho "%query"',
      'search_hot_title': '🔥 Được tìm nhiều nhất',
      'search_input_prompt': 'Nhập từ khóa để tìm phim',
      'clear_filter': 'Xóa lọc',
      'category_label': 'Thể loại: %name',
      'views_count': '%count lượt',
      'movie_series': 'Phim bộ',
      'movie_single': 'Phim lẻ',
      'year_label': 'Năm %year',
      'today': 'Hôm nay',
      'loading_schedule': 'Đang tải lịch chiếu...',
      'no_schedule_today': 'Hôm nay chưa có lịch chiếu',
      'no_schedule_date': 'Không có lịch chiếu vào %date',
      'unknown_episode': 'Tập ???',
      'watching': 'Đang xem',
      'my_list_long': 'Danh sách phim của tôi',
      'tv_login': 'Đăng nhập SmartTV',
      'fb_fanpage': 'Fanpage Facebook',
      'tg_channel': 'Kênh Telegram',
      'tg_support': 'Nhóm Telegram (Hỗ trợ)',
      'terms_of_service': 'Điều khoản dịch vụ',
      'privacy_policy': 'Chính sách bảo mật',
      'forgot_password': 'Quên mật khẩu?',
      'exact_alarm_permission_denied': 'Thiếu quyền đặt báo thức.',
      'notification_permission_denied': 'Quyền thông báo bị từ chối.',
      'notification_scheduled': 'Đã đặt nhắc nhở 🔔',
      'notification_cancelled': 'Đã hủy nhắc nhở',
      'notification_time_passed': 'Thời gian chiếu đã trôi qua',
      'broadcast_reminder_title': 'Sắp công chiếu: %name%',
      'broadcast_reminder_body':
          '%movie% sẽ bắt đầu sau %minutes% phút nữa. Đừng bỏ lỡ nhé!',
      'view_movie_detail': 'Xem chi tiết',
      'bg_new_episode_title_simple': 'Tập mới: %n%',
      'broadcast_now_title': 'Bắt đầu công chiếu: %name%',
      'broadcast_now_body': 'Phim %movie% đang được công chiếu. Xem ngay thôi!',
      'download_fetching_playlist': 'Đang lấy thông tin...',
      'download_downloading_segments': 'Đang tải %c/%t...',
      'download_merging_video': 'Đang ghép video...',

      'save_changes': 'Lưu thay đổi',
      'not_open_link': 'Không thể mở liên kết',
      'close': 'Đóng',
      'cannot_download_update': 'Không thể tải bản cập nhật. Vui lòng thử lại!',
      'download_failed_network':
          'Tải thất bại: Lỗi kết nối mạng (Kiểm tra Wifi/4G) 🌐',
      'download_failed_server':
          'Tải thất bại: Lỗi máy chủ (Vui lòng thử lại sau) 🚫',
      'update_checking': 'Đang kiểm tra phiên bản mới...',
      'login_required_favorites': 'Vui lòng đăng nhập để xem phim yêu thích.',
      'login_required_history': 'Vui lòng đăng nhập để xem lịch sử phim.',
      'error_unknown': 'Đã xảy ra lỗi không xác định',
      'resolver_error': 'Lỗi resolver: %error',
      'no_sources_found': 'Không tìm thấy nguồn phát hợp lệ cho tập này.',
      'all_sources_failed': 'Tất cả các nguồn phát đều thất bại.',
      'player_source_fallback':
          'Nguồn lỗi, đang thử nguồn %current%/%total%...',
      'TXA_PB1': 'Phim bộ mới',
      'TXA_PL1': 'Phim lẻ mới',
      'TXA_NEW1': 'Phim mới cập nhật',
      'TXA_HOT1': 'Phim hot',
      'TXA_HH1': 'Anime & Hoạt hình',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Phim chiếu rạp',
      'TXA_LIST1': 'Danh sách phim',
      'player_brightness': 'Độ sáng',
      'player_audio': 'Âm thanh',
      'player_speed': 'Tốc độ phát',
      'loading_video': 'Đang tải video...',
      'player_lock': 'Khóa màn hình',
      'player_unlock': 'Mở khóa',
      'player_play': 'Phát',
      'player_pause': 'Tạm dừng',
      'player_close': 'Đóng phim',
      'player_show_clock': 'Đồng hồ',
      'player_clock_format': 'Định dạng giờ',
      'player_dnd_auto': 'Tự động "Không làm phiền"',
      'auto_pip_label': 'Tự động bật PiP',
      'miracast_detected':
          'Phát hiện phản chiếu màn hình. Vui lòng tắt Miracast để tiếp tục xem.',
      'auto_pip_desc':
          'Tự động kích hoạt thu nhỏ màn hình khi thoát app đang xem phim',
      'permission_overlay_label': 'Cấp quyền hiển thị',
      'player_episodes': 'Danh sách tập',
      'player_gesture_hint': 'Vuốt để chỉnh độ sáng/âm lượng',
      'player_fast_forward_2x': 'Đang tua nhanh 2x',
      'player_seek_forward': 'Tua tới %count giây',
      'player_seek_backward': 'Tua lùi %count giây',
      'player_watermark': 'TPhimX Premium',
      'player_ratio': 'Tỷ lệ',
      'player_audio_track': 'Âm thanh',
      'player_seek_hint_short': 'Chạm đúp',
      'player_subtitle': 'Phụ đề',
      'player_system_control_blocked':
          'App đang điều khiển hệ thống, không thể chỉnh tay',
      'player_start_in': 'Bắt đầu sau',
      'prev_ep': 'Tập trước',
      'next_ep': 'Tập tiếp',
      'current_label': 'Hiện tại',
      'server_switch_hint': 'Chọn server để xem ở nguồn khác',
      'server_ep_unavailable_title': 'Tập phim không khả dụng',
      'server_ep_unavailable_msg':
          'Tập %ep chưa có trên server %server. Tự động chuyển về server mặc định.',
      'player_position': 'Tiến độ phát',
      'download_finished': 'Tải xong 🚀',
      'click_to_install': '(Bấm để cài đặt)',
      'verifying_file': 'Đang xác minh bản cập nhật...',
      'installing_cached': 'Bản cập nhật đã sẵn sàng, đang mở trình cài đặt...',
      'error_opening_link': 'Không thể mở trình cài đặt hoặc liên kết',
      'udid_register_title': 'Nhập mã UDID',
      'udid_update_title': 'Cập nhật UDID',
      'udid_hint': 'Dán mã UDID tại đây...',
      'udid_save': 'Lưu lại',
      'udid_copy': 'Sao chép UDID',
      'udid_copied': 'Đã sao chép UDID',
      'udid_deleted': '✅ Đã xóa UDID!',
      'udid_delete_btn': 'Xóa UDID',
      'udid_install_btn': 'Cài đặt ngay',
      'udid_get_btn': 'Lấy UDID',
      'udid_input_btn': 'Nhập UDID',
      'udid_update_btn': 'Cập nhật',
      'udid_registered_badge': 'ĐÃ ĐĂNG KÝ',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc':
          'Cần đăng ký UDID thiết bị để có thể cài đặt và cập nhật bản IPA Premium chính thức.',
      'ios_ready_desc':
          'Thiết bị của bạn đã được đăng ký UDID. Bạn có thể cài đặt phiên bản Premium IPA chính thức ngay bây giờ.',
      'premium_tab': 'Premium',
      'share_logs': 'Chia sẻ nhật ký',
      'share_logs_desc':
          'Gửi file log qua AirDrop, tin nhắn hoặc lưu vào Files',
      'share_logs_subject': 'TPhimX Log Files',
      'udid_auto_detected': '✅ Tự động nhận diện UDID thành công!',
      'udid_invalid': '❌ Mã UDID không hợp lệ: %m',
      'status_registered': 'Đã đăng ký',
      'status_not_registered': 'Chưa đăng ký',
      'notifications': 'Thông báo',
      'error_loading_notifications': 'Không thể tải thông báo',
      'login': 'Đăng nhập',
      'register': 'Đăng ký',
      'login_id': 'Tên tài khoản hoặc Email',
      'login_id_hint': 'Nhập username hoặc email của bạn',
      'password': 'Mật khẩu',
      'password_hint': 'Nhập mật khẩu của bạn',
      'create_account': 'Tạo tài khoản',
      'full_name': 'Họ và tên',
      'email': 'Email',
      'username': 'Tên tài khoản',
      'confirm_password': 'Xác nhận mật khẩu',
      'gender': 'Giới tính',
      'gender_male': 'Nam',
      'gender_female': 'Nữ',
      'gender_other': 'Khác',
      'no_notifications': 'Bạn chưa có thông báo nào',
      'error_login': 'Đăng nhập thất bại',
      'error_register': 'Đăng ký thất bại',
      'verify_email_msg': 'Vui lòng xác minh email để đăng nhập',
      'login_success': 'Đăng nhập thành công',
      'register_success': 'Đăng ký thành công',
      'logout_success': 'Đăng xuất thành công',
      'logout_confirm': 'Bạn có chắc chắn muốn đăng xuất?',
      'account_title': 'Tài khoản',
      'email_verified': 'Đã xác minh email',
      'verified_email_success': 'Xác minh email thành công!',
      'verify_now': 'Xác minh ngay',
      'app_slogan': 'Phim mới cực mượt - Xem là ghiền',
      'error_empty_fields': 'Vui lòng điền đầy đủ các trường',
      'error_password_mismatch': 'Mật khẩu xác nhận không khớp',
      'error_connection': 'Lỗi kết nối máy chủ',
      'login_required_notifications': 'Vui lòng đăng nhập để xem thông báo.',
      'favorite_added': 'Đã thêm vào yêu thích ❤️',
      'favorite_removed': 'Đã xóa khỏi yêu thích',
      'my_list': 'Danh sách của tôi',
      'notifications_cleared': 'Đã xóa tất cả thông báo',
      'notifications_read_all': 'Đã đánh dấu tất cả là đã đọc',
      'appearance': 'Giao diện',
      'settings': 'Cài đặt',
      'font_size': 'Cỡ chữ',
      'font_size_desc': 'Điều chỉnh kích thước văn bản toàn ứng dụng',
      'font_family': 'Phông chữ',
      'font_outfit': 'Outfit (Mặc định)',
      'font_roboto': 'Roboto',
      'font_inter': 'Inter',
      'font_open_sans': 'Open Sans',
      'font_montserrat': 'Montserrat',
      'font_oswald': 'Oswald',
      'font_playfair': 'Playfair Display',
      'font_poppins': 'Poppins',
      'font_lato': 'Lato',
      'font_nunito': 'Nunito',
      'font_merriweather': 'Merriweather',
      'font_manrope': 'Manrope',
      'font_rubik': 'Rubik',
      'font_fira_sans': 'Fira Sans',
      'font_source_sans_3': 'Source Sans 3',
      'font_plus_jakarta_sans': 'Plus Jakarta Sans',
      'font_bebas_neue': 'Bebas Neue',
      'cache_management': 'Quản lý bộ nhớ đệm',
      'clear_cache': 'Xóa bộ nhớ đệm',
      'cache_cleared': 'Đã xóa bộ nhớ đệm thành công',
      'cache_empty': 'Bộ nhớ đệm trống',
      'cache_size': 'Dung lượng bộ nhớ: %size%',
      'permissions': 'Quền hạn & Bảo mật',
      'manage_permissions': 'Quản lý quyền ứng dụng',
      'manage_permissions_desc':
          'Mở cài đặt hệ thống để cấp/hủy các quyền đã yêu cầu',
      'reminder_set': 'Đã đặt nhắc nhở 🔔',
      'reminder_canceled': 'Đã hủy nhắc nhở',
      'delete_all': 'Xóa hết',
      'read_all': 'Đọc hết',
      'unread': 'Chưa đọc',
      'marked_read': 'Đã đọc',
      'permission_dnd_label': 'Quyền Không làm phiền',
      'permission_dnd_desc':
          'Bắt buộc để ứng dụng có thể tự động bật chế độ im lặng khi bạn xem phim, giúp trải nghiệm không bị gián đoạn.',
      'permission_alarm_label': 'Báo thức chính xác',
      'permission_alarm_desc': 'Bắt buộc để gửi thông báo lịch chiếu đúng giờ.',
      'view_all': 'Xem tất cả',
      'no_favorites': 'Chưa có phim yêu thích',
      'no_history': 'Lịch sử xem trống',
      'system': 'Hệ thống',
      'network_speed': 'Tốc độ mạng',
      'auto_quality': 'Tự động chất lượng',
      'auto_quality_desc': 'Tự động tối ưu chất lượng dựa trên tốc độ mạng',
      'show_speed_notif': 'Hiện tốc độ thông báo',
      'show_speed_notif_desc':
          'Hiện chỉ báo tốc độ trên thanh trạng thái & màn hình khóa',
      'speed_unit': 'Đơn vị tốc độ',
      'battery_optimization': 'Bỏ tối ưu pin (Chạy ngầm)',
      'ignore_battery_msg':
          'Để tốc độ mạng luôn chính xác và tải phim ổn định, vui lòng cho phép ứng dụng bỏ qua tối ưu hóa pin.',
      'episode_label': 'Tập %n%',
      'time_hour': '%n% giờ',
      'time_minute': '%n% phút',
      'time_second': '%n% giây',
      'time_just_now': 'Vừa xong',
      'time_seconds_ago': '%n% giây trước',
      'time_minutes_ago': '%n% phút trước',
      'time_hours_ago': '%n% giờ trước',
      'time_days_ago': '%n% ngày trước',
      'time_months_ago': '%n% tháng trước',
      'time_years_ago': '%n% năm trước',
      'num_k': 'K',
      'num_m': 'Tr',
      'num_b': 'Tỷ',
      'miracast_protection': 'Bảo vệ Miracast',
      'cast_to_tv': 'Phát lên TV',
      'speed_test': 'Kiểm tra tốc độ',
      'network': 'Mạng',
      'start_test': 'Bắt đầu đo',
      'network_wifi': 'WiFi',
      'network_mobile': 'Dữ liệu di động',
      'network_ethernet': 'Cáp mạng (Ethernet)',
      'network_usage': 'Lưu lượng đã dùng',
      'total': 'Tổng cộng',
      'testing': 'Đang đo...',
      'miracast_mirror': 'Miracast / Screen Mirror',
      'miracast_mirror_desc': 'Mở cài đặt phản chiếu hệ thống',
      'chromecast_desc': 'Phát video trực tiếp lên thiết bị Chromecast',
      'web_browser_cast': 'Dò Web (Browser)',
      'web_browser_cast_desc':
          'Mở link video trong trình duyệt có hỗ trợ truyền tải',
      'block_mirroring': 'Chặn phản chiếu (Bảo vệ)',
      'protection_on': 'Bảo vệ Miracast: BẬT (Chặn phản chiếu)',
      'protection_off': 'Bảo vệ Miracast: TẮT (Cho phép phản chiếu)',
      'searching_chromecast': 'Đang tìm kiếm thiết bị Chromecast...',
      'found_chromecast': 'Tìm thấy %n% thiết bị!',
      'no_chromecast_found': 'Không tìm thấy thiết bị nào.',
      'bg_new_episode_title': 'Tập mới: %n%',
      'bg_new_episode_body': 'Phim bạn yêu thích vừa có tập mới!',
      'select_device': 'Chọn thiết bị (%count)',
      'disconnect_cast': 'Ngắt kết nối Cast',
      'casting_to': 'Đang truyền tới',
      'no_streamable_url': 'Không tìm thấy link video để truyền',
      'stopped_casting': 'Đã dừng truyền video',
      'download_settings': 'Cài đặt tải xuống',
      'download_format': 'Định dạng video',
      'max_concurrent_downloads': 'Số tập tải cùng lúc',
      'download_queue': 'Hàng đợi tải',
      'download_path': 'Đường dẫn lưu trữ',
      'downloaded_series_progress': 'Đã tải %p%% (Tập %c%/%t%)',
      'download_completed': 'Tải hoàn tất',
      'download_channel_name': 'Quản lý tải xuống',
      'download_channel_desc': 'Thông báo về tiến độ và trạng thái tải phim',
      'download_all_completed': 'Đã tải xong tất cả %n% tập',
      'download_single_completed': 'Đã tải xong tập: %ep%',
      'download_error': 'Lỗi khi tải: %msg%',
      'delete_all_confirm': 'Xóa tất cả phim đã tải?',
      'delete_movie_confirm': 'Xóa phim này khỏi máy?',
      'offline_mode': 'Đang xem ngoại tuyến',
      'movie_removed_server': 'Phim đã bị gỡ khỏi Server. Tự động xóa sau 5s.',
      'priority_download': 'Tải ngay (Ưu tiên)',
      'storage_full': 'Bộ nhớ đầy, không thể tải thêm',
      'download_manager': 'Quản lý tải xuống',
      'cancel_download': 'Hủy tải',
      'pause_download': 'Tạm dừng',
      'resume_download': 'Tiếp tục',
      'all_episodes': 'tất cả tập',
      'adding_all_to_download': 'Đang thêm tất cả tập vào hàng chờ tải...',
      'cannot_download_episode': 'Không thể tải tập phim. Vui lòng thử lại!',
      'download_link_not_found': 'Không tìm thấy link tải cho tập phim này',
      'added_to_download': 'Đã thêm vào hàng chờ tải 📥',
      'download_all_started': 'Đã thêm %n% tập vào hàng chờ tải',
      'download_all_failed':
          'Không thể thêm tập phim nào. Kiểm tra kết nối mạng!',
      'download_all_partial': 'Đã thêm %s%/%t% tập. %f% tập thất bại',
      'downloading_all': 'Đang xử lý tải tất cả...',
      'no_internet_no_downloads': 'Không có kết nối & Chưa có phim tải về',
      'no_internet_msg':
          'Vui lòng kiểm tra kết nối internet để xem phim trực tuyến hoặc tải phim về xem ngoại tuyến.',
      'download_speed': 'Tốc độ: %s%',
      'episodes_count': 'Tập: %c%/%t%',
      'total_size': 'Dung lượng: %s% / %t%',
      'downloaded_movies': 'Phim đã tải',
      'episode_count_label': '%n% tập',
      'downloaded': 'Đã tải về',
      'delete': 'Xóa',
      'local_playback_error':
          'Lỗi phát file cục bộ. File có thể bị hỏng hoặc thiếu dữ liệu (HLS segments).',
      'test_completed': 'Kiểm tra hoàn tất',
      'test_again': 'Đo lại',
      'speed_excellent': 'Tuyệt vời! Mượt mà cho 4K.',
      'speed_good': 'Rất tốt. Mượt mà cho HD.',
      'speed_stable': 'Ổn định. Tốt cho SD.',
      'speed_slow': 'Kết nối chậm. Có thể giật lag.',
      'api_server': 'Server API',
      'image_server': 'Server Ảnh',
      'no_notifications_desc': 'Bạn chưa có thông báo nào mới. Hãy theo dõi các bộ phim yêu thích để nhận tin tức mới nhất!',
    },
    'en': {
      'preparing': 'Preparing...',
      'logout': 'Logout',
      'app_name': 'TPhimX Premium',
      'ok': 'OK',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'check_update': 'Check for Updates',
      'downloading': 'Downloading',
      'download_fetching_playlist': 'Fetching playlist...',
      'download_downloading_segments': 'Downloading %c/%t...',
      'download_merging_video': 'Merging video...',
      'downloading_status': 'Downloading: %p%% • %s% • ETA: %e%',
      'error': 'Error',
      'success': 'Success',
      'permissions_required': 'Permissions Required',
      'storage_permission_msg':
          'App needs file management permission to save logs and download apps.',
      'grant': 'Grant',
      'skip': 'Skip',
      'retry': 'Retry',
      'network_error': 'No network connection',
      'update_available': 'New update available',
      'update_now': 'Update Now',
      'later': 'Later',
      'no_movies': 'No movies found',
      'error_loading_data': 'Failed to load data',
      'no_changelog': 'No update history available',
      'new_update_movies': 'Newest Movies',
      'hot_movies': 'Hot Movies',
      'anime_cartoon': 'Anime & Animation',
      'series_movies': 'New Series',
      'single_movies': 'New Singles',
      'cartoon_movies': 'Cartoons',
      'tv_shows': 'TV Shows',
      'theater_movies': 'Theaters',
      'search': 'Search',
      'home': 'Home',
      'categories': 'Categories',
      'schedule': 'Schedule',
      'logs': 'Logs',
      'clear_logs_confirm': 'Clear all logs?',
      'clear_logs_msg': 'This will delete all existing log files.',
      'profile': 'Profile',
      'app_premium': 'Mobile Premium',
      'connecting': 'Connecting...',
      'retry_connection': 'Retry Connection',
      'more': 'More',
      'watch_now': 'Watch now',
      'add_favorite': 'Favorite',
      'trending_categories': 'What are you interested in?',
      'see_all': 'See All',
      'permission_storage_label': 'Storage & File Management',
      'permission_storage_desc':
          'Required to download movies and save app logs.',
      'permission_notif_label': 'Push Notifications',
      'permission_notif_desc':
          'Receive notifications for new episodes or schedules.',
      'permission_install_label': 'Install Applications',
      'permission_install_desc': 'Required for automatic version upgrades.',
      'permission_overlay_desc':
          'Required for Picture-in-Picture mode to work when leaving the app.',
      'permission_nearby_devices_label': 'Nearby Devices',
      'permission_nearby_devices_desc':
          'Required to search and connect to Cast/TV devices in the local network.',
      'permission_bluetooth_label': 'Bluetooth (Scanning)',
      'permission_bluetooth_desc':
          'Necessary to detect wireless casting devices nearby.',
      'permission_nearby_devices_denied':
          'Nearby devices permission denied. Cannot scan for TV.',
      'pip_permission_missing': 'Missing overlay permission for Auto PiP.',
      'press_back_again': 'Press back again to exit',
      'player_settings': 'Player Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'vi_lang': 'Vietnamese',
      'en_lang': 'English',
      'loading_progress': 'Preparing data...',
      'splash_check_permissions': 'Checking permissions...',
      'splash_init_language': 'Initializing language...',
      'splash_config_system': 'Configuring system...',
      'splash_init_download': 'Initializing downloader...',
      'splash_ios_no_access': 'You do not have access to this application.',
      'splash_init_failed': 'Initialization failed',
      'splash_error_title': 'Oops! Something went wrong',
      'splash_error_copy': 'Copy Error',
      'splash_error_copied': 'Error code copied!',
      'splash_browser_error': 'Could not open browser',
      'splash_get_access': 'Get app access',
      'splash_safari_note':
          'Note: You need to install the verification profile after Safari opens.',
      'maintenance_title': 'System Under Maintenance',
      'maintenance_msg':
          'We are upgrading our system to provide a better experience. Please check back in a few minutes.',
      'check_permissions': 'Checking permissions',
      'please_grant_all': 'Please grant required permissions to continue.',
      'go_to_settings': 'Go to Settings',
      'permissions_mandatory': 'Mandatory Permissions',
      'permissions_optional': 'Optional Permissions',
      'granted': 'Granted',
      'denied': 'Denied',
      'continue': 'Continue',
      'permission_location_label': 'Location',
      'permission_location_desc':
          'Required for accurate network speed testing.',
      'permission_nearby_label': 'Nearby Devices',
      'permission_nearby_desc': 'Used to find and cast video to TV.',
      'speed_test_error':
          'Could not start speed test. Please grant location permission or try again later.',
      'feature_dev': 'Feature under development',
      'feature_under_dev': 'Feature "%label" is under development',
      'coming_soon': 'Coming Soon',
      'coming_soon_msg':
          'This feature will be available in future updates. Please check back later!',
      'episodes': 'Episodes',
      'episode': 'Episode',
      'loading_home': 'Loading homepage...',
      'loading_movie': 'Loading movie info...',
      'all_movies_count': '%count movies',
      'recommendation': 'Suggestions',
      'no_episodes': 'No episodes available',
      'not_found_movie': 'Movie not found',
      'select_server': 'Select Server',
      'related_parts': 'Which part?',
      'series_parts': 'Which part?',
      'actors': 'Cast',
      'no_actors': 'No cast info available',
      'download': 'Download',
      'download_label': 'Download speed',
      'upload_label': 'Upload speed',
      'share': 'Share',
      'favorite_list': 'Favorites',
      'collapse': 'Collapse',
      'show_more': 'Show more',
      'broadcast_msg': '%prefix% will broadcast at %time%. Don\'t miss it 😙',
      'broadcast_final_msg':
          'Don\'t miss %prefix% (Final) broadcasting at %time% 🥹',
      'broadcast_suffix':
          'Next episode will broadcast at %time%. Stay tuned 😙',
      'final_ep': 'Final Episode',
      'final_part': 'Final',
      'current_version': 'Current Version: %version%',
      'update_history': 'Update History',
      'general_settings': 'General Settings',
      'app_settings': 'App Settings',
      'community_support': 'Community & Support',
      'legal': 'Legal',
      'clear_cache_msg':
          'Are you sure you want to clear all temporary files and cache?',
      'cache_cleared': 'Cache cleared',
      'session_expired': 'Session Expired',
      'load_error': 'Failed to load information',
      'login_again_msg': 'Please login again to continue',
      'up_to_date': 'You are on the latest version (%version%)',
      'update_error': 'Failed to check for updates',
      'checking_update': 'Checking for new version...',
      'whats_new': 'What\'s new:',
      'version_label': 'Version %version%',
      'volume': 'Volume',
      'speed': 'Speed',
      'skip_intro': 'Skip Intro',
      'auto_next_ep': 'Auto Next Episode',
      'skip_outro_next': 'Skip Outro / Next',
      'prep_next_ep': 'Preparing next episode...',
      'video_error': 'Failed to load video. Please try again!',
      'search_hint': 'Search movies, actors...',
      'searching': 'Searching...',
      'search_results': 'Results (%count)',
      'search_no_results': 'No results found for "%query"',
      'search_hot_title': '🔥 Trending Searches',
      'search_input_prompt': 'Types keywords to find movies',
      'clear_filter': 'Clear filter',
      'category_label': 'Category: %name',
      'views_count': '%count views',
      'movie_series': 'Series',
      'movie_single': 'Single',
      'year_label': 'Year %year',
      'today': 'Today',
      'loading_schedule': 'Loading schedule...',
      'no_schedule_today': 'No schedule today',
      'no_schedule_date': 'No schedule on %date',
      'unknown_episode': 'Episode ???',
      'watching': 'Watching',
      'my_list_long': 'My Movie List',
      'tv_login': 'SmartTV Login',
      'fb_fanpage': 'Facebook Fanpage',
      'tg_channel': 'Telegram Channel',
      'tg_support': 'Telegram Support',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'forgot_password': 'Forgot Password?',
      'account_title': 'Account',
      'save_changes': 'Save Changes',
      'not_open_link': 'Could not open link',
      'close': 'Close',
      'cannot_download_update': 'Could not download update',
      'download_failed_network': 'Download failed: Network error 🌐',
      'download_failed_server': 'Download failed: Server error (404/500) 🚫',
      'login_required_favorites': 'Please login to view favorites.',
      'login_required_history': 'Please login to view watch history.',
      'error_unknown': 'An unknown error occurred',
      'resolver_error': 'Resolver error: %error',
      'no_sources_found': 'No valid streaming sources found for this episode.',
      'all_sources_failed': 'All streaming sources failed to load.',
      'player_source_fallback':
          'Source failed, trying source %current%/%total%...',
      'TXA_PB1': 'New Series',
      'TXA_PL1': 'New Singles',
      'TXA_NEW1': 'Newly Updated',
      'TXA_HOT1': 'Hot Movies',
      'TXA_HH1': 'Anime & Cartoons',
      'TXA_TV1': 'TV Shows',
      'TXA_CR1': 'Theatrical Movies',
      'TXA_LIST1': 'Movie List',
      'player_brightness': 'Brightness',
      'player_audio': 'Audio',
      'player_speed': 'Playback Speed',
      'loading_video': 'Loading video...',
      'player_lock': 'Lock Screen',
      'player_unlock': 'Unlock',
      'player_play': 'Play',
      'player_pause': 'Pause',
      'player_close': 'Close Player',
      'player_show_clock': 'Clock',
      'player_clock_format': 'Clock Format',
      'player_dnd_auto': 'Auto "Do Not Disturb"',
      'auto_pip_label': 'Auto PiP Mode',
      'auto_pip_desc':
          'Automatically minimize to a floating window when leaving the app while watching',
      'permission_overlay_label': 'Display permission',
      'player_episodes': 'Episode List',
      'player_gesture_hint': 'Swipe to adjust brightness/volume',
      'player_fast_forward_2x': 'Fast Forwarding 2x',
      'player_seek_forward': 'Seek forward %count s',
      'miracast_detected':
          'Screen mirroring detected. Please disable Miracast to continue.',
      'player_seek_backward': 'Seek backward %count s',
      'player_watermark': 'TPhimX Premium',
      'player_ratio': 'Ratio',
      'player_audio_track': 'Audio',
      'player_seek_hint_short': 'Double Tap',
      'player_subtitle': 'Subtitle',
      'player_system_control_blocked':
          'Controlled by app, manual change disabled',
      'player_start_in': 'Starts in',
      'prev_ep': 'Prev Ep',
      'next_ep': 'Next Ep',
      'current_label': 'Current',
      'server_switch_hint': 'Switch server to watch from another source',
      'server_ep_unavailable_title': 'Episode Unavailable',
      'server_ep_unavailable_msg':
          'Episode %ep is not available on %server. Auto-switching to default server.',
      'player_position': 'Playback position',
      'download_finished': 'Download finished 🚀',
      'click_to_install': '(Click to install)',
      'verifying_file': 'Verifying update file...',
      'installing_cached': 'Update ready, opening installer...',
      'error_opening_link': 'Could not open installer or link',
      'udid_register_title': 'Input UDID',
      'udid_update_title': 'Update UDID',
      'udid_hint': 'Paste UDID here...',
      'udid_save': 'Save',
      'udid_copy': 'Copy UDID',
      'udid_copied': 'UDID copied',
      'udid_deleted': '✅ UDID deleted!',
      'udid_delete_btn': 'Delete UDID',
      'udid_install_btn': 'Install Now',
      'udid_get_btn': 'Get UDID',
      'udid_input_btn': 'Input UDID',
      'udid_update_btn': 'Update',
      'udid_registered_badge': 'REGISTERED',
      'ios_service_title': 'iOS Premium Service',
      'ios_premium_desc':
          'Need to register device UDID to install and update the official Premium IPA.',
      'ios_ready_desc':
          'Your device is registered. You can install the official Premium IPA now.',
      'premium_tab': 'Premium',
      'share_logs': 'Share Logs',
      'share_logs_desc':
          'Send log files via AirDrop, messages or save to Files',
      'no_logs_found': 'No log files found',
      'share_logs_subject': 'TPhimX Log Files',
      'udid_auto_detected': '✅ UDID auto-detected successfully!',
      'udid_invalid': '❌ Invalid UDID code: %m',
      'status_registered': 'Registered',
      'status_not_registered': 'Not Registered',
      'notifications': 'Notifications',
      'error_loading_notifications': 'Could not load notifications',
      'screenshot_detected': 'Screenshot detected',
      'share_screenshot': 'Share screenshot',
      'pip_mode': 'PiP Mode',
      'now_playing_pip': 'Now playing: %title%',
      'exact_alarm_permission_denied': 'Missing exact alarm permission.',
      'notification_permission_denied': 'Notification permission denied.',
      'notification_scheduled': 'Reminder set 🔔',
      'notification_cancelled': 'Reminder cancelled',
      'notification_time_passed': 'Broadcast time has passed',
      'update_checking': 'Checking for new version...',
      'login': 'Login',
      'register': 'Register',
      'login_id': 'Username or Email',
      'login_id_hint': 'Enter your username or email',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'create_account': 'Create Account',
      'full_name': 'Full Name',
      'email': 'Email',
      'username': 'Username',
      'confirm_password': 'Confirm Password',
      'gender': 'Gender',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'gender_other': 'Other',
      'no_notifications': 'No notifications found',
      'no_notifications_desc': 'New notifications will appear here.',
      'error_login': 'Login failed',
      'error_register': 'Registration failed',
      'verify_email_msg': 'Please verify your email to login',
      'login_success': 'Login successful',
      'register_success': 'Registration successful',
      'logout_success': 'Logout successful',
      'logout_confirm': 'Are you sure you want to logout?',
      'email_verified': 'Email verified',
      'verified_email_success': 'Email verified successfully!',
      'verify_now': 'Verify now',
      'app_slogan': 'Smooth streaming - Watch and crave',
      'error_empty_fields': 'Please fill in all fields',
      'error_password_mismatch': 'Confirm password does not match',
      'error_connection': 'Server connection error',
      'login_required_notifications': 'Please login to view notifications.',
      'favorite_added': 'Added to favorites ❤️',
      'favorite_removed': 'Removed from favorites',
      'my_list': 'My List',
      'notifications_cleared': 'All notifications cleared',
      'notifications_read_all': 'All marked as read',
      'appearance': 'Appearance',
      'settings': 'Settings',
      'font_size': 'Font Size',
      'font_size_desc': 'Adjust the text size across the entire app',
      'font_family': 'Font Family',
      'font_outfit': 'Outfit (Default)',
      'font_roboto': 'Roboto',
      'font_inter': 'Inter',
      'font_open_sans': 'Open Sans',
      'font_montserrat': 'Montserrat',
      'font_oswald': 'Oswald',
      'font_playfair': 'Playfair Display',
      'font_poppins': 'Poppins',
      'font_lato': 'Lato',
      'font_nunito': 'Nunito',
      'font_merriweather': 'Merriweather',
      'font_manrope': 'Manrope',
      'font_rubik': 'Rubik',
      'font_fira_sans': 'Fira Sans',
      'font_source_sans_3': 'Source Sans 3',
      'font_plus_jakarta_sans': 'Plus Jakarta Sans',
      'font_bebas_neue': 'Bebas Neue',
      'cache_management': 'Cache Management',
      'clear_cache': 'Clear Cache',
      'cache_empty': 'Cache is empty',
      'cache_size': 'Cache size: %size%',
      'reminder_set': 'Reminder set 🔔',
      'reminder_canceled': 'Reminder canceled',
      'broadcast_reminder_title': 'Upcoming: %name%',
      'broadcast_reminder_body':
          '%movie% will start in %minutes% minutes. Don\'t miss it!',
      'view_movie_detail': 'View Detail',
      'bg_new_episode_title_simple': 'New Episode: %n%',
      'broadcast_now_title': 'Now Broadcasting: %name%',
      'broadcast_now_body': 'Movie %movie% is now broadcasting. Watch now!',
      'delete_all': 'Clear All',
      'read_all': 'Read All',
      'unread': 'Unread',
      'marked_read': 'Read',
      'permission_dnd_label': 'Do Not Disturb Permission',
      'permission_dnd_desc': 'Allow app to manage notification sounds.',
      'permission_alarm_label': 'Exact Alarm',
      'permission_alarm_desc':
          'Required to send showtime notifications on time.',
      'view_all': 'View all',
      'no_favorites': 'No favorites yet',
      'no_history': 'Empty watch history',
      'permissions': 'Permissions & Security',
      'manage_permissions': 'Manage App Permissions',
      'manage_permissions_desc':
          'Open system settings to grant or revoke requested permissions',
      'system': 'System',
      'network_speed': 'Network Speed',
      'auto_quality': 'Auto Quality',
      'auto_quality_desc':
          'Automatically optimize quality based on network speed',
      'show_speed_notif': 'Show speed in notification',
      'show_speed_notif_desc':
          'Show speed indicator on status bar & lock screen',
      'speed_unit': 'Speed Unit',
      'battery_optimization': 'Ignore Battery Optimization',
      'ignore_battery_msg':
          'To ensure accurate network speed and stable downloads, please allow the app to ignore battery optimization.',
      'episode_label': 'Episode %n%',
      'time_hour': '%n%h',
      'time_minute': '%n%m',
      'time_second': '%n%s',
      'time_just_now': 'Just now',
      'time_seconds_ago': '%n%s ago',
      'time_minutes_ago': '%n%m ago',
      'time_hours_ago': '%n%h ago',
      'time_days_ago': '%n%d ago',
      'time_months_ago': '%n%mo ago',
      'time_years_ago': '%n%y ago',
      'num_k': 'K',
      'num_m': 'M',
      'num_b': 'B',
      'miracast_protection': 'Miracast Protection',
      'cast_to_tv': 'Cast to TV',
      'speed_test': 'Speed Test',
      'network': 'Network',
      'start_test': 'Start Test',
      'network_wifi': 'WiFi',
      'network_mobile': 'Mobile Data',
      'network_ethernet': 'Ethernet',
      'network_usage': 'Data Usage',
      'total': 'Total',
      'testing': 'Testing...',
      'miracast_mirror': 'Miracast / Screen Mirror',
      'miracast_mirror_desc': 'Open system screen mirroring settings',
      'chromecast_desc': 'Stream directly to Chromecast devices',
      'web_browser_cast': 'Web Browser (Cast)',
      'web_browser_cast_desc':
          'Open video link in browser with casting support',
      'block_mirroring': 'Block Mirroring (Protection)',
      'protection_on': 'Protection: ON (Block mirroring)',
      'protection_off': 'Protection: OFF (Allow mirroring)',
      'searching_chromecast': 'Searching for Chromecast devices...',
      'found_chromecast': 'Found %n% devices!',
      'no_chromecast_found': 'No devices found.',
      'bg_new_episode_title': 'New Episode: %n%',
      'bg_new_episode_body': 'Your favorite movie just got a new episode!',
      'select_device': 'Select device (%count)',
      'disconnect_cast': 'Disconnect Cast',
      'casting_to': 'Casting to',
      'no_streamable_url': 'No streamable URL found for casting',
      'stopped_casting': 'Stopped casting',
      'download_settings': 'Download Settings',
      'download_format': 'Video Format',
      'max_concurrent_downloads': 'Concurrent Downloads',
      'download_queue': 'Download Queue',
      'download_path': 'Storage Path',
      'downloaded_series_progress': 'Downloaded %p%% (Ep %c%/%t%)',
      'download_completed': 'Download Completed',
      'download_channel_name': 'Download Management',
      'download_channel_desc': 'Notifications for download progress and status',
      'download_all_completed': 'All %n% episodes downloaded',
      'download_single_completed': 'Downloaded episode: %ep%',
      'download_error': 'Download error: %msg%',
      'delete_all_confirm': 'Delete all downloaded movies?',
      'delete_movie_confirm': 'Delete this movie from device?',
      'offline_mode': 'Offline Playback',
      'movie_removed_server': 'Movie removed from server. Deleting in 5s.',
      'priority_download': 'Download Now (Priority)',
      'storage_full': 'Storage full, cannot download',
      'download_manager': 'Download Manager',
      'cancel_download': 'Cancel',
      'pause_download': 'Pause',
      'resume_download': 'Resume',
      'all_episodes': 'all episodes',
      'adding_all_to_download': 'Adding all episodes to download queue...',
      'cannot_download_episode':
          'Could not download episode. Please try again!',
      'download_link_not_found': 'Download link not found for this episode',
      'added_to_download': 'Added to download queue 📥',
      'download_all_started': 'Added %n% episodes to download queue',
      'download_all_failed': 'Could not add any episodes. Check your network!',
      'download_all_partial': 'Added %s%/%t% episodes. %f% failed',
      'downloading_all': 'Processing download all...',
      'no_internet_no_downloads': 'No Connection & No Downloads',
      'no_internet_msg':
          'Please check your internet connection to watch online or download movies for offline viewing.',
      'download_speed': 'Speed: %s%',
      'episodes_count': 'Episodes: %c%/%t%',
      'total_size': 'Size: %s% / %t%',
      'downloaded_movies': 'Downloaded Movies',
      'episode_count_label': '%n% episodes',
      'downloaded': 'Downloaded',
      'delete': 'Delete',
      'local_playback_error':
          'Local playback error. File might be corrupted or missing data (HLS segments).',
    },
  };

  static String get currentLang => _currentLang;

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString('txa_lang');
    if (saved != null) {
      _currentLang = saved;
    } else {
      // Automatic detection
      try {
        final locale = Platform.localeName.split('_')[0];
        if (_dicts.containsKey(locale)) {
          _currentLang = locale;
        } else {
          _currentLang = 'en'; // Default
        }
      } catch (_) {
        _currentLang = 'vi';
      }
    }
  }

  static Future<void> setLang(String lang) async {
    if (_dicts.containsKey(lang)) {
      _currentLang = lang;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('txa_lang', lang);
      _instance.notifyListeners();
      onLanguageChanged?.call();
    }
  }

  static String t(String key, {Map<String, String>? replace}) {
    if (_dicts[_currentLang]?[key] == null) {
      TxaLogger.log(
        "Missing key '$key' for language '$_currentLang'",
        isError: true,
      );
    }
    String text = _dicts[_currentLang]?[key] ?? _dicts['en']?[key] ?? key;
    if (replace != null) {
      replace.forEach((k, v) {
        text = text.replaceAll('%$k%', v);
      });
    }
    return text;
  }
}
